# Assignment

Import numpy as np

In [3]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
l1=[1,2,3,4,5]
a=np.array(l1)
print(a)

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [5]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(matrix1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [6]:
a=np.arange(1,18,2)
a.reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [7]:
np.random.randn(10)

array([ 0.51178337,  0.68754766, -1.56580793,  0.38061104,  0.80845824,
        0.8847466 , -0.26930143,  0.83438683, -1.66926503, -0.87104349])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [8]:
a=np.array([1,2,3,4,5])
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [9]:
a.shape

(5,)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [10]:
a=np.arange(1,11)
print(a)
print(a[2])
print(a[3])
print(a[8])

[ 1  2  3  4  5  6  7  8  9 10]
3
4
9


Print alternate elements of that array

In [11]:
print(a[0:10:2])

[1 3 5 7 9]


Change last 3 elements into 100 using broadcasting and print

In [12]:
a[7:10]=100
a

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [13]:
a=np.arange(1,26)
a1=a.reshape(5,5)
print(a1)
a1[1:4,1:4]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])